@echo off
setlocal enabledelayedexpansion
rem setup.cmd -- first-time (or "setup.cmd --force" re-key) setup.
rem Mirrors setup.sh. Prompts passphrase + API key, wraps X25519 identity,
rem seeds config tree from templates\windows, encrypts into config\claude.age.

set "SCRIPT_DIR=%~dp0"
if "%SCRIPT_DIR:~-1%"=="\" set "SCRIPT_DIR=%SCRIPT_DIR:~0,-1%"
set "VENDOR_DIR=%SCRIPT_DIR%\vendor\win32-x64"
set "AGE_BIN=%VENDOR_DIR%\age.exe"
set "AGE_KEYGEN=%VENDOR_DIR%\age-keygen.exe"
set "CONFIG_DIR=%SCRIPT_DIR%\config"
set "TEMPLATE_DIR=%SCRIPT_DIR%\templates\windows"

set "FORCE=0"
if /i "%~1"=="--force" set "FORCE=1"

rem -- Preflight ---------------------------------------------------------
if not exist "%AGE_BIN%" (
  echo ERROR: %AGE_BIN% not found.
  echo Run scripts\build-windows.sh on a Linux build host first.
  pause
  exit /b 1
)
if not exist "%AGE_KEYGEN%" (
  echo ERROR: %AGE_KEYGEN% not found.
  pause
  exit /b 1
)
if exist "%CONFIG_DIR%\claude.age" if not "%FORCE%"=="1" (
  echo ERROR: %CONFIG_DIR%\claude.age already exists.
  echo Use: setup.cmd --force to overwrite ^(destroys existing session state^).
  pause
  exit /b 1
)
if not exist "%CONFIG_DIR%" mkdir "%CONFIG_DIR%"
if exist "%CONFIG_DIR%\claude.age.new" del /f /q "%CONFIG_DIR%\claude.age.new"

rem -- Temp workspace ----------------------------------------------------
set "TMPD=%CONFIG_DIR%\.setup-tmp"
if exist "%TMPD%" rmdir /s /q "%TMPD%"
mkdir "%TMPD%"
mkdir "%TMPD%\seed\claude\skills"
set "TAR_TMP=%TMPD%\seed.tar"

rem -- 1. Generate identity ---------------------------------------------
echo ==^> Generating X25519 identity...
"%AGE_KEYGEN%" -o "%TMPD%\identity.plain" 2>nul
if errorlevel 1 (
  echo ERROR: age-keygen failed.
  goto :fail
)

rem Avoid the triply-nested quoted for-backtick pattern by going through a file.
"%AGE_KEYGEN%" -y "%TMPD%\identity.plain" > "%TMPD%\recipient.tmp" 2>nul
set /p RECIPIENT=<"%TMPD%\recipient.tmp"
if "!RECIPIENT!"=="" (
  echo ERROR: could not derive public key from identity.
  goto :fail
)

rem -- 2. Wrap identity with passphrase ---------------------------------
echo ==^> Wrapping identity with passphrase...
if defined CLAUDE_DROPIN_PASSPHRASE (
  rem Non-interactive: plugin path. %%VAR%% ^(not !VAR!^) to preserve any `!` in pw.
  set "PATH=%VENDOR_DIR%;%PATH%"
  set "AGE_PASSPHRASE=%CLAUDE_DROPIN_PASSPHRASE%"
  "%AGE_BIN%" -e -j batchpass -o "%CONFIG_DIR%\identity.age" "%TMPD%\identity.plain"
  set "RC=!ERRORLEVEL!"
  set "AGE_PASSPHRASE="
  if not "!RC!"=="0" (
    echo ERROR: identity wrap failed ^(rc=!RC!^).
    goto :fail
  )
) else (
  echo.
  echo You'll choose a passphrase now. There is no recovery path -- if you
  echo forget it, the encrypted state is permanently unreadable.
  echo.
  "%AGE_BIN%" -p -o "%CONFIG_DIR%\identity.age" "%TMPD%\identity.plain" 2>"%TMPD%\age.err"
  if errorlevel 1 (
    type "%TMPD%\age.err"
    echo.
    echo ERROR: identity wrap failed.
    goto :fail
  )
  findstr /c:"using autogenerated passphrase" "%TMPD%\age.err" >nul
  if not errorlevel 1 (
    del /f /q "%CONFIG_DIR%\identity.age" 2>nul
    echo.
    echo ERROR: empty passphrase not allowed ^(age auto-generated one, unrecoverable^).
    echo Re-run setup.cmd and enter a passphrase you'll remember.
    goto :fail
  )
)

rem -- 3. Write recipient.pub -------------------------------------------
^> "%CONFIG_DIR%\recipient.pub" echo !RECIPIENT!

rem -- 4. Seed scratch tree ---------------------------------------------
if defined CLAUDE_DROPIN_API_KEY (
  ^> "%TMPD%\seed\api-key" echo(!CLAUDE_DROPIN_API_KEY!
) else (
  echo.
  rem PowerShell Read-Host -AsSecureString hides input; convert to plaintext.
  for /f "usebackq delims=" %%k in (`powershell -NoProfile -Command ^
    "$s = Read-Host -AsSecureString 'Enter Anthropic API key (blank for OAuth)'; if ($s.Length -gt 0) { [Runtime.InteropServices.Marshal]::PtrToStringBSTR([Runtime.InteropServices.Marshal]::SecureStringToBSTR($s)) }"`) do set "API_KEY=%%k"
  if defined API_KEY (
    ^> "%TMPD%\seed\api-key" echo(!API_KEY!
    set "API_KEY="
  )
)

if exist "%TEMPLATE_DIR%\settings.json"  copy /y "%TEMPLATE_DIR%\settings.json"  "%TMPD%\seed\claude\settings.json" >nul
if exist "%TEMPLATE_DIR%\CLAUDE.md"      copy /y "%TEMPLATE_DIR%\CLAUDE.md"      "%TMPD%\seed\claude\CLAUDE.md"     >nul
if exist "%TEMPLATE_DIR%\skills"         xcopy /e /i /y /q "%TEMPLATE_DIR%\skills" "%TMPD%\seed\claude\skills" >nul

rem -- 5. Encrypt seed into claude.age (two-step: tar-archive then age) -
echo ==^> Encrypting initial session state...
pushd "%TMPD%\seed"
tar -c -f "%TAR_TMP%" .
set "RC=!ERRORLEVEL!"
popd
if not "!RC!"=="0" (
  echo ERROR: tar create failed ^(rc=!RC!^).
  goto :fail
)
"%AGE_BIN%" -e -r "!RECIPIENT!" -o "%CONFIG_DIR%\claude.age.new" "%TAR_TMP%"
set "RC=!ERRORLEVEL!"
if not "!RC!"=="0" (
  echo ERROR: encryption failed ^(rc=!RC!^).
  if exist "%CONFIG_DIR%\claude.age.new" del /f /q "%CONFIG_DIR%\claude.age.new"
  goto :fail
)
move /y "%CONFIG_DIR%\claude.age.new" "%CONFIG_DIR%\claude.age" >nul

rem -- 6. Cleanup --------------------------------------------------------
rmdir /s /q "%TMPD%"

echo.
echo Setup complete.
echo   config\identity.age   -- X25519 identity wrapped with your passphrase
echo   config\recipient.pub  -- public key (cleartext; safe)
echo   config\claude.age     -- encrypted initial session state
echo.
echo Launch with: run.cmd
echo Rekey with:  setup.cmd --force
endlocal
exit /b 0

:fail
if exist "%TMPD%" rmdir /s /q "%TMPD%"
if exist "%CONFIG_DIR%\claude.age.new" del /f /q "%CONFIG_DIR%\claude.age.new"
endlocal
exit /b 1
