#!/usr/bin/env bash
# lib/common.sh — shared helpers for run.sh / setup.sh / eject.sh.
# Source this; don't run directly.

# Caller must: `set -euo pipefail` before sourcing.

# resolve_script_dir PATH — echoes absolute dir after resolving symlinks.
# Typical use: SCRIPT_DIR="$(resolve_script_dir "${BASH_SOURCE[0]}")"
resolve_script_dir() {
  local src="$1"
  (cd -- "$(dirname -- "$(readlink -f -- "$src")")" && pwd)
}

# locate_scratch_dir CONFIG_DIR — pick and mkdir a scratch dir; echo its path.
# Prefers /dev/shm for RAM-backing; falls back to $CONFIG_DIR/scratch.
# Any prior content at the chosen path is shredded first.
locate_scratch_dir() {
  local config_dir="$1"
  local chosen
  if [[ -d /dev/shm && -w /dev/shm ]]; then
    chosen="/dev/shm/claude-dropin.$$"
  else
    chosen="$config_dir/scratch"
  fi
  [[ -d "$chosen" ]] && shred_dir "$chosen"
  mkdir -p "$chosen"
  chmod 700 "$chosen"
  printf '%s\n' "$chosen"
}

# prompt_password [PROMPT] — read a passphrase from /dev/tty silently; echo to stdout.
prompt_password() {
  local prompt="${1:-Passphrase: }"
  local pw
  IFS= read -r -s -p "$prompt" pw </dev/tty
  printf '\n' >&2
  printf '%s' "$pw"
}

# prompt_password_confirmed [PROMPT] — prompts twice, aborts on mismatch or empty.
prompt_password_confirmed() {
  local prompt="${1:-Passphrase: }"
  local pw1 pw2
  pw1="$(prompt_password "$prompt")"
  pw2="$(prompt_password "Confirm:    ")"
  if [[ "$pw1" != "$pw2" ]]; then
    echo "Passphrases don't match." >&2
    return 1
  fi
  if [[ -z "$pw1" ]]; then
    echo "Empty passphrase not allowed." >&2
    return 1
  fi
  printf '%s' "$pw1"
}

# wrap_identity AGE_BIN PLUGIN_DIR IDENTITY_PLAIN OUT_FILE [PASSPHRASE]
#   Encrypt an identity file with a passphrase.
#   If PASSPHRASE is non-empty, use age-plugin-batchpass (non-interactive).
#   Otherwise use `age -p` which prompts on /dev/tty; captures stderr to
#   detect age's "empty passphrase → autogenerate" footgun and aborts if hit.
wrap_identity() {
  local age_bin="$1" plugin_dir="$2" identity_plain="$3" out="$4" pw="${5:-}"
  if [[ -n "$pw" ]]; then
    PATH="$plugin_dir:$PATH" AGE_PASSPHRASE_FD=3 \
      "$age_bin" -e -j batchpass -o "$out" "$identity_plain" 3<<<"$pw"
    return
  fi
  # Interactive path — no plugin, just native age -p.
  # age writes the prompt + reads input on /dev/tty; stderr gets the
  # "using autogenerated passphrase" warning if the user leaves it blank.
  local errf
  errf="$(mktemp)"
  if ! "$age_bin" -p -o "$out" "$identity_plain" 2>"$errf"; then
    cat "$errf" >&2
    rm -f "$errf" "$out"
    return 1
  fi
  if grep -qi "using autogenerated passphrase" "$errf"; then
    rm -f "$errf" "$out"
    echo "ERROR: empty passphrase not allowed." >&2
    echo "       age auto-generated one, which we cannot recover." >&2
    echo "       Re-run setup and enter a passphrase you'll remember." >&2
    return 1
  fi
  rm -f "$errf"
}

# decrypt_identity AGE_BIN PLUGIN_DIR IDENTITY_AGE OUT [PASSPHRASE]
#   Decrypt the passphrase-wrapped identity file to OUT.
#   If PASSPHRASE is non-empty, use age-plugin-batchpass (non-interactive);
#   otherwise age prompts on /dev/tty.
decrypt_identity() {
  local age_bin="$1" plugin_dir="$2" identity_age="$3" out="$4" pw="${5:-}"
  if [[ -n "$pw" ]]; then
    PATH="$plugin_dir:$PATH" AGE_PASSPHRASE_FD=3 \
      "$age_bin" -d -j batchpass -o "$out" "$identity_age" 3<<<"$pw"
  else
    "$age_bin" -d -o "$out" "$identity_age"
  fi
}

# decrypt_blob AGE_BIN CONFIG_DIR SCRATCH PLUGIN_DIR AGE_KEYGEN [PASSPHRASE]
#   Decrypt config/claude.age into SCRATCH. If PASSPHRASE is empty,
#   age prompts on /dev/tty.
#
#   SECURITY: verifies that the decrypted identity's public key matches
#   config/recipient.pub. If it doesn't, someone tampered with recipient.pub
#   (key-swap attack) — refuse to decrypt. Running with a bad recipient.pub
#   would silently re-encrypt session state to the attacker's key on exit.
decrypt_blob() {
  local age_bin="$1" config_dir="$2" scratch="$3" plugin_dir="$4" age_keygen="$5" pw="${6:-}"
  local tmpid
  tmpid="$(mktemp --tmpdir="$(dirname "$scratch")" .identity.XXXXXX)"
  chmod 600 "$tmpid"
  decrypt_identity "$age_bin" "$plugin_dir" "$config_dir/identity.age" "$tmpid" "$pw"

  # Key-swap attack guard.
  local derived_pub expected_pub
  derived_pub="$("$age_keygen" -y "$tmpid")"
  expected_pub="$(cat "$config_dir/recipient.pub")"
  if [[ "$derived_pub" != "$expected_pub" ]]; then
    shred -fun 1 "$tmpid" 2>/dev/null || rm -f "$tmpid"
    echo "ERROR: config/recipient.pub does not match the identity's public key." >&2
    echo "       Possible tampering (key-swap attack). Refusing to continue." >&2
    echo "       Inspect the folder; if legitimate, re-run ./setup.sh --force." >&2
    return 1
  fi

  # Pipe failure detection: with 'set -o pipefail' the caller catches age's
  # non-zero rc; without pipefail, we'd silently accept an empty decrypt.
  # Callers are required to have pipefail set.
  "$age_bin" -d -i "$tmpid" "$config_dir/claude.age" | tar -x -C "$scratch"
  shred -fun 1 "$tmpid" 2>/dev/null || rm -f "$tmpid"
}

# cleanup_stale_new CONFIG_DIR — remove any claude.age.new left by a crashed encrypt.
cleanup_stale_new() {
  local config_dir="$1"
  rm -f "$config_dir/claude.age.new"
}

# encrypt_blob AGE_BIN CONFIG_DIR SCRATCH
#   Tar scratch contents, encrypt to recipient.pub, atomic-swap into config/claude.age.
#   No passphrase needed (public-key recipient).
encrypt_blob() {
  local age_bin="$1" config_dir="$2" scratch="$3"
  local recipient
  recipient="$(cat "$config_dir/recipient.pub")"
  tar -C "$scratch" -cf - . \
    | "$age_bin" -e -r "$recipient" -o "$config_dir/claude.age.new"
  mv -f "$config_dir/claude.age.new" "$config_dir/claude.age"
}

# shred_dir DIR — best-effort secure wipe of regular files, then rm -rf.
shred_dir() {
  local dir="$1"
  [[ -d "$dir" ]] || return 0
  find "$dir" -type f -exec shred -fun 1 {} + 2>/dev/null || true
  rm -rf "$dir"
}

# assert_file_sha256 FILE EXPECTED_HASH — aborts on mismatch.
assert_file_sha256() {
  local file="$1" expected="$2"
  local actual
  actual="$(sha256sum "$file" | awk '{print $1}')"
  if [[ "$actual" != "$expected" ]]; then
    echo "ERROR: SHA256 mismatch for $file" >&2
    echo "  expected: $expected" >&2
    echo "  actual:   $actual" >&2
    return 1
  fi
}

# download_and_verify URL OUT_PATH EXPECTED_SHA256
#   Curl the URL to OUT_PATH, then verify SHA256. Rm the file if verification fails.
download_and_verify() {
  local url="$1" out="$2" expected="$3"
  curl -fsSL --retry 3 -o "$out" "$url"
  if ! assert_file_sha256 "$out" "$expected"; then
    rm -f "$out"
    return 1
  fi
}
